### ISSUE TITLE
Multiple dex files define 

### ISSUE THREAD

**Issue by 10045125** [facebook/Sonar#117]
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lokhttp3/internal/http2/Http2Connection$ReaderRunnable$1;
Error:com.android.dex.DexException: Multiple dex files define Lokhttp3/internal/http2/Http2Connection$ReaderRunnable$1;

Sonar need complie okhttp

**Comment by priteshrnandgaonkar** [comment]
Hi, Can you try using `0.0.8`? Follow the discussion #24

**Comment by passy** [comment]
That's definitely for the old version. Let's close this in favour of #24.
