### ISSUE TITLE
Update version in fbsonar (0.0.1)

### ISSUE THREAD

**Issue by yschimke** [facebook/Sonar#121]
https://fbsonar.com/docs/getting-started.html

**Comment by passy** [comment]
Sorry, which version number?

**Comment by yschimke** [comment]
This page was 0.0.1 this morning, now 0.0.8

```
dependencies {
  debugImplementation 'com.facebook.sonar:sonar:0.0.8'
}
```

**Comment by yschimke** [comment]
https://github.com/facebook/Sonar/commit/e11a587426d675ca06c6459fb962aec746c9794b#diff-a39c9f7aa728d5fa3b973bc6ba49228a

**Comment by passy** [comment]
Ah, sorry. Didn't take the time into account. That diff had been sitting there since Friday. :)
