### ISSUE TITLE
Sonar network plugin drops events on view change

### ISSUE THREAD

**Issue by yschimke** [facebook/Sonar#123]
https://github.com/facebook/Sonar/blob/master/android/plugins/network/NetworkSonarPlugin.java

is a BufferingSonarPlugin, so obviously it's intended to not lose events before you connect.  However if you change views to use another plugin and return the events disappear.  This doesn't appear to be intentional.

**Comment by danielbuechele** [comment]
fixed in c239fcac01331523bfb17b97f39fee3a1694f759
