### ISSUE TITLE
Swift support for Sonar

### ISSUE THREAD

**Issue by priteshrnandgaonkar** [facebook/Sonar#13]
Currently Sonar doesn't build with Swift projects due to its dependecies being written in c++.
There are few files which are referenced by sonar's Objective-C wrapper which has reference to header with C++ code. We can either get rid off those references from header files to support swift.

**Comment by bolismauro** [comment]
Is there any plan to fix this or an ETA? The tool seems extremely powerful and interesting and I have several use cases for it but unfortunately our projects are swift only

**Comment by sergeyzenchenko** [comment]
@bolismauro you can try https://appspector.com instead. Works with swift and has more features :)

**Comment by sergeyzenchenko** [comment]
interesting, are you looking for some specific feature? @bolismauro

**Comment by bolismauro** [comment]
I want to play with layout editor and the ability of developing custom things within the tool.
Also I prefer not to go trough a 3rd party service I cannot control.

I think this isn't the proper place to discuss this though. Let's keep it clean for the sonar swift support

**Comment by priteshrnandgaonkar** [comment]
@bolismauro Currently its isn't in our internal roadmap.We would expect open source community to fix it. But seeing on how things pan out we may end up working on it. But I can't see that happen soon.

**Comment by bolismauro** [comment]
Gotcha. I unfortunately don't have strong c++ knowledge but I think I'll try anyway. Do you have some suggestions about how to proceed and what need to be fixed?

**Comment by priteshrnandgaonkar** [comment]
Just try and get rid off the c++ in the header files of sonar. In header files you may also find other inported dependency that has c++ in it. So one has to create a c wrapper over it and then use in the public headers of sonar.Basically we have to make sure that headers doesn't have c++ in it.

**Comment by noahsark769** [comment]
I took a look into building Sonar for use in [Trestle](https://appstore.com/trestle), which is a Swift project. As far as I can see, Cocoapods should be able to configure the Sonar/SonarKit pods into modules which Swift can use using `:modular_headers => true`. Swift projects use pods which have C++ in them all the time - [Sentry](https://github.com/getsentry/sentry-cocoa) is a good example of a pod which has no Swift and some C++ and is usuable from a Swift project.

Here's what my Podfile looks like:

```
  pod 'RSocket', :podspec => 'https://raw.githubusercontent.com/facebook/Sonar/master/iOS/third-party-podspecs/RSocket.podspec'
  pod 'DoubleConversion', :podspec => 'https://raw.githubusercontent.com/facebook/Sonar/master/iOS/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => 'https://raw.githubusercontent.com/facebook/Sonar/master/iOS/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => 'https://raw.githubusercontent.com/facebook/Sonar/master/iOS/third-party-podspecs/Folly.podspec'
  pod 'PeerTalk', :podspec => 'https://raw.githubusercontent.com/facebook/Sonar/master/iOS/third-party-podspecs/PeerTalk.podspec'
  pod 'Yoga','~>1.8.1', :modular_headers => true
  pod 'Sonar', :podspec => 'https://raw.githubusercontent.com/facebook/Sonar/master/xplat/Sonar/Sonar.podspec'
  pod 'SonarKit', :podspec => 'https://raw.githubusercontent.com/facebook/Sonar/master/iOS/SonarKit.podspec', :modular_headers => true
  pod 'SonarKit/SonarKitLayoutComponentKitSupport', :podspec => 'https://raw.githubusercontent.com/facebook/Sonar/master/iOS/SonarKit.podspec'
  pod 'SonarKit/SKIOSNetworkPlugin', :podspec => 'https://raw.githubusercontent.com/facebook/Sonar/master/iOS/SonarKit.podspec'
  pod 'ComponentKit', :podspec => 'https://raw.githubusercontent.com/facebook/Sonar/master/iOS/third-party-podspecs/ComponentKit.podspec'

  post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
      if ['YogaKit'].include? target.name
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '3.0.2'
          end
      end
    end
  end
```

Not running into any errors due to C++ used in headers like @priteshrnandgaonkar said, however I'm seeing the same error as in #28 (`'iosfwd' file not found`). Here's the full trace:

```
/Users/noahgilmore/code/trest-ios/Trest/../Pods/Headers/Public/SonarKit/SonarCppBridgingConnection.h:8:9: note: while building module 'Sonar' imported from /Users/noahgilmore/code/trest-ios/Trest/../Pods/Headers/Public/SonarKit/SonarCppBridgingConnection.h:8:
#import <Sonar/SonarConnection.h>
        ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Sonar-umbrella.h"
        ^
/Users/noahgilmore/code/trest-ios/Trest/../Pods/Headers/Public/Sonar/Sonar-umbrella.h:14:9: note: in file included from /Users/noahgilmore/code/trest-ios/Trest/../Pods/Headers/Public/Sonar/Sonar-umbrella.h:14:
#import "SonarClient.h"
        ^
/Users/noahgilmore/code/trest-ios/Trest/../Pods/Headers/Public/Sonar/SonarClient.h:11:10: note: in file included from /Users/noahgilmore/code/trest-ios/Trest/../Pods/Headers/Public/Sonar/SonarClient.h:11:
#include <Sonar/SonarConnectionImpl.h>
         ^
/Users/noahgilmore/code/trest-ios/Trest/../Pods/Headers/Public/Sonar/SonarConnectionImpl.h:11:10: note: in file included from /Users/noahgilmore/code/trest-ios/Trest/../Pods/Headers/Public/Sonar/SonarConnectionImpl.h:11:
#include <Sonar/SonarConnection.h>
         ^
/Users/noahgilmore/code/trest-ios/Trest/../Pods/Headers/Public/Sonar/SonarConnection.h:11:10: note: in file included from /Users/noahgilmore/code/trest-ios/Trest/../Pods/Headers/Public/Sonar/SonarConnection.h:11:
#include <Sonar/SonarResponder.h>
         ^
/Users/noahgilmore/code/trest-ios/Trest/../Pods/Headers/Public/Sonar/SonarResponder.h:11:10: note: in file included from /Users/noahgilmore/code/trest-ios/Trest/../Pods/Headers/Public/Sonar/SonarResponder.h:11:
#include <folly/json.h>
         ^
/Users/noahgilmore/code/trest-ios/Trest/../Pods/Headers/Public/Folly/folly/json.h:43:10: error: 'iosfwd' file not found
#include <iosfwd>
         ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "SonarKit-umbrella.h"
        ^
/Users/noahgilmore/code/trest-ios/Trest/../Pods/Headers/Public/SonarKit/SonarKit-umbrella.h:13:9: note: in file included from /Users/noahgilmore/code/trest-ios/Trest/../Pods/Headers/Public/SonarKit/SonarKit-umbrella.h:13:
#import "SonarCppBridgingConnection.h"
        ^
/Users/noahgilmore/code/trest-ios/Trest/../Pods/Headers/Public/SonarKit/SonarCppBridgingConnection.h:8:9: error: could not build module 'Sonar'
#import <Sonar/SonarConnection.h>
        ^
/Users/noahgilmore/code/trest-ios/Trest/Trest/AppDelegate.swift:16:8: error: could not build Objective-C module 'SonarKit'
import SonarKit
       ^
```

I could be wrong but the solution to this might just be an include path configuration fix. Any advice here is appreciated :) @bolismauro were you able to make any headway here?

**Comment by bolismauro** [comment]
It works perfectly! 
Thanks a lot for have worked on this, I struggled to find the proper time and it is great that you guys are pushing this forward :)

**Comment by Suil3File** [comment]
Amazing
