### ISSUE TITLE
Android plugin can't browse db/SharedPreference like Stetho

### ISSUE THREAD

**Issue by b95505017** [facebook/Sonar#139]
Does this feature will be support officially or we have to implement ourself?

**Comment by danielbuechele** [comment]
A plugin for shared preferences is open-sourced in the next hours!

**Comment by b95505017** [comment]
@danielbuechele Thanks, what about database?

**Comment by danielbuechele** [comment]
We don't have such a plugin currently. That means, it would be up to the community to build one. However, I know @xiphirx was interested in building one.

**Comment by b95505017** [comment]
Interesting, @xiphirx Looking forward to it!

**Comment by vincent-paing** [comment]
Any update on this?

**Comment by xiphirx** [comment]
I haven't had time to work on the DB plugin, mostly because I cant get Flipper to work on my Windows machine at home :( I still plan on doing it though.

**Comment by chainchelliah** [comment]
Any update on this?

**Comment by disparate** [comment]
Also, in Stetho I had ability to browse shared preferences of inner libs (for example of analytics libs) and it was very usefull. Can we get the same result using Flipper?

**Comment by xiphirx** [comment]
You can add multiple shared preference files by specifying multiple `SharedPreferencesDescriptor`s https://github.com/facebook/flipper/blob/master/android/src/main/java/com/facebook/flipper/plugins/sharedpreferences/SharedPreferencesFlipperPlugin.java#L92
