### ISSUE TITLE
error: isMainProcess(Context) has private access in SonarUtils

### ISSUE THREAD

**Issue by andreiverdes** [facebook/Sonar#14]
Pretty explanatory from the title :D 
Trying to setup Sonar and I'm having a compile issue

**Comment by Rohfosho** [comment]
You can use `SonarUtils.shouldEnableClient(this)` instead. 

This checks if it's the main process, an end to end test, and if it's an internal build.

**Comment by andreiverdes** [comment]
Oh okay, then :) the getting started guide was using that, closing this issue
