### ISSUE TITLE
App caught in upgrade loop

### ISSUE THREAD

**Issue by ronocod** [facebook/Sonar#140]
I had 0.6.9 of the app installed, then it updated. The new version says it's 0.6.0 and displays this on startup:
![screen shot 2018-07-05 at 11 41 06](https://user-images.githubusercontent.com/466546/42318907-567fefe6-8048-11e8-94a8-57a06b10b2fb.png)

When the app relaunches after clicking `Install and Restart` the same dialog displays, and the loop continues.

**Comment by priteshrnandgaonkar** [comment]
cc @danielbuechele

**Comment by ronocod** [comment]
Version has reverted to 0.6.9 for me and I'm not seeing this any more

**Comment by danielbuechele** [comment]
Version 0.6.12 is now released that should fix the problem. If you are still caught in an update loop, just download the latest version from GitHbu releases.
