### ISSUE TITLE
Don't log connection failures so aggressively

### ISSUE THREAD

**Issue by danh32** [facebook/Sonar#142]
On Android, logcat output is being spammed with:
```
I  sonar: Requesting fresh certificate exchange after 246 failed connection attempts
I  sonar: Starting certificate exchange
I  sonar: Error connecting to sonar
I  sonar: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused)
I  sonar: error code: 0
```

whenever the Sonar desktop app isn't connected. It's really distracting, and making it harder to debug our app's logcat output. Would be great to make this much less aggressive.

**Comment by jknoxville** [comment]
Hey @danh32, this was fixed in https://github.com/facebook/Sonar/commit/f7d487dd7607226858ecb3380b889969d5e9a073#diff-21c6ae41362f1b7ca59c9a6e163a500cL118

It looks like you're using a pretty old version of the sdk. Out of curiosity did you build it from source or get it from jCenter?

**Comment by danh32** [comment]
Ah my bad! Didn't realize there were new releases since they weren't listed here: https://github.com/facebook/Sonar/releases

No we're not building from source, just depending on an old release.
