### ISSUE TITLE
Failed to resolve: sonar:third-party:unspecified

### ISSUE THREAD

**Issue by b95505017** [facebook/Sonar#162]
This is what dependencies tree look like in android library:

```
+--- com.facebook.sonar:sonar:0.6.12
|    +--- com.facebook.sonar:fbjni:0.6.12
|    |    \--- com.facebook.soloader:soloader:0.5.0
|    +--- sonar:third-party:unspecified FAILED
```

**Comment by yschimke** [comment]
Workaround?

```
  implementation('com.facebook.sonar:sonar:0.6.12') {
    exclude group: 'sonar'
  }
```

**Comment by passy** [comment]
Wouldn't that also exclude fbjni?

I think you would also want to specify `module: 'third-party'` to be safe.

But yeah, this is not ideal. I'll need to restructure our modules to avoid that.

**Comment by yschimke** [comment]
fbjni group is com.facebook.sonar, so it's ok.
