### ISSUE TITLE
ndk armeabi missing 

### ISSUE THREAD

**Issue by Whoisurdady** [facebook/Sonar#177]
In our project, we use ndk like this 
ndk {
            abiFilters "armeabi"
 }, and it make a "Class not found exception".
And i found Sonar does not have armeabi libs.
Now i manualy copy libs to armeabi, but it is not friendly to other developers in our project.
Will sonar solve this problem in recent release ?

**Comment by passy** [comment]
`armeabi` was deprecated in NDK r16 and removed in r17. We currently don't have any plans on supporting it. It should still be possible to manually build Sonar and the extensions by pointing it at an older SDK and setting the appropriate `abiFilters`.

**Comment by Whoisurdady** [comment]
All right, may be i can try to write a script or sth to do this~~
Thank u all the way~~
