### ISSUE TITLE
Link to download latest build for desktop app in "Getting Started" broken.

### ISSUE THREAD

**Issue by KevCron** [facebook/Sonar#179]
Steps to reproduce:

- Click on ["Getting Started"](https://fbsonar.com/docs/getting-started.html) from README.
- Click on the link ["download the latest build"](https://www.facebook.com/sonar/public/mac)
- Observe that the link does not go anywhere.

https://fbsonar.com/docs/getting-started.html
https://www.facebook.com/sonar/public/mac <---- 404's.

**Comment by passy** [comment]
@priteshrnandgaonkar fixed this. :)
