### ISSUE TITLE
Crash on launch, no mention of SoLoader in getting started

### ISSUE THREAD

**Issue by hibob224** [facebook/Sonar#27]
When following the Android getting started guide I'm running into the following exception when launching the app

```
AndroidRuntime	FATAL EXCEPTION: SonarEventBaseThread
Process: com.example.sonartest, PID: 11228
java.lang.ExceptionInInitializerError
	at com.facebook.sonar.android.SonarThread.run(SonarThread.java:25)
Caused by: java.lang.RuntimeException: SoLoader.init() not yet called
	at com.facebook.soloader.SoLoader.assertInitialized(SoLoader.java:746)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:476)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:455)
	at com.facebook.jni.HybridData.<clinit>(HybridData.java:34)
	... 1 more
```

Looking at the sample [application](https://github.com/facebook/Sonar/blob/master/android/sample/src/sonar/com/facebook/sonar/sample/SonarSampleApplication.java#L30) it seems necessary to call `SoLoader.init()` prior to creating a Sonar client, if this is the case the [getting started guide](https://fbsonar.com/docs/getting-started.html) should be updated to reflect this.

**Comment by jknoxville** [comment]
Thanks Jonathan, for anyone else hitting this, as you pointed out in #36 
the correct way to avoid this is to initialize SoLoader at app startup.
See the sample app for an example: https://github.com/facebook/Sonar/blob/master/android/sample/src/sonar/com/facebook/sonar/sample/SonarSampleApplication.java#L30

I'll update the docs shortly.

**Comment by jknoxville** [comment]
Getting started page updated in 28be3c7cd85c43880f37f170b14c39403e07458e
