### ISSUE TITLE
Android compilation error using it with React Native module libgnustl_shared.so, libfb.so duplication

### ISSUE THREAD

**Issue by pranayairan** [facebook/Sonar#32]
When integrating Sonar on a project with React Native as a dependency, I get a lot of **DuplicateRelativeFileException** with libgnustl_shared, libfb etc. 

This is happening due to the dependency of our app on React Native. I was able to fix this issue by putting this in our gradle file 

```
android {
        packagingOptions {
            pickFirst 'lib/armeabi-v7a/libgnustl_shared.so'
            pickFirst 'lib/x86/libgnustl_shared.so'
            pickFirst 'lib/armeabi-v7a/libfb.so'
            pickFirst 'lib/x86/libfb.so'
            pickFirst 'lib/armeabi-v7a/libglog.so'
            pickFirst 'lib/x86/libglog.so'
        }
    }
```
Submitting the issue so others can fix it.

**Comment by pranayairan** [comment]
i am still having different issues after making the change, I am unable to run it. I sometimes get this error 
`Multiple dex files define Lcom/facebook/jni/Countable;`

Sometimes there is a different error but the same type of Multiple dex files define. Would be good to have a solution to get Sonar work with RN based android app.

**Comment by passy** [comment]
The underlying issue here is probably #41 too, but worth keeping around separately.

**Comment by passy** [comment]
This should no longer be a thing as we've renamed our version of `libfb.so`. #24 should take care of the remaining issues.
