### ISSUE TITLE
Support Desktop app on Linux

### ISSUE THREAD

**Issue by toantk238** [facebook/Sonar#35]
Do you have any plan to make this app runnable on Linux system ( for me, I'm using Ubuntu 18.04 ).

Curl 7.60.0
Yarn 1.7.0

I tried to run it then got this error.

> yarn
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-config-fbjs@2.0.1" has incorrect peer dependency "babel-eslint@^7.2.3".
[4/4] Building fresh packages...
$ node node_modules/electron/install.js && node scripts/yarn-install.js
warning "metro > @babel/plugin-check-constants@7.0.0-beta.38" has incorrect peer dependency "@babel/core@7.0.0-beta.38".
📦  Installed all dependencies!
Done in 62.17s.

> yarn start
Error: watch Sonar/node_modules/handlebars/dist/cjs/handlebars/helpers ENOSPC
    at _errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at NodeWatcher.watchdir (Sonar/static/node_modules/sane/src/node_watcher.js:175:20)
    at Walker.<anonymous> (Sonar/static/node_modules/sane/src/common.js:127:12)
    at emitTwo (events.js:126:13)
    at Walker.emit (events.js:214:7)
    at Sonar/static/node_modules/walker/lib/walker.js:69:16
    at FSReqWrap.oncomplete (fs.js:135:15)
error Command failed with exit code 1

**Comment by danielbuechele** [comment]
Is this a bug other users are experiencing, too? We created a linux build and were not facing this error. The `ENOSPC` looks like the file watcher is watching too many files.

**Comment by passy** [comment]
Just tried building on my box and both `yarn start` and `yarn build` work fine. I reckon this is file handle limits as @danielbuechele said. Check what `ulimit -n` says and if it's a low number (< 100000), then you'll likely run into those kinda problems.

**Comment by toantk238** [comment]
@passy 
Oh, it works :+1: 
I tried to increase "fs.file-max" in "/etc/sysctl.conf" file and now everything seems OK.

Thank you so much.

@danielbuechele 
Thank you too.

**Comment by koox00** [comment]
I get this error when running `yarn`.
`7zip-bin-mac@1.0.1: The platform "linux" is incompatible with this module.`
it fails to install dependencies.

**Comment by danielbuechele** [comment]
This shouldn't break the build. Can you post the full error message?

**Comment by koox00** [comment]
yarn install v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
error 7zip-bin-mac@1.0.1: The platform "linux" is incompatible with this module.
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by danielbuechele** [comment]
For now you can use remove this dependency. It is not needed in your case. This should fix the build for you, while I try to find a solution to this.

**Comment by danielbuechele** [comment]
should be fixed in #6f95ad5
