### ISSUE TITLE
Cannot compile Android project with D8 Compiler

### ISSUE THREAD

**Issue by vincent-paing** [facebook/Sonar#38]
I can't seem to build the project after adding Sonar and enabling d8 compiler in gradle.properties with 
 ```android.enableD8=true```. I got the following error when I run with ```gradlew clean assemble```

```
> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
D8: Program type already present: android.support.v4.app.BackStackRecord$Op
```
Removing Sonar dependency in gradle and running again works. Happening on Android Studio 3.2 with SDK Version of 28

**Comment by passy** [comment]
Closing in favour of #41.
