### ISSUE TITLE
Support library classes are packaged into AAR

### ISSUE THREAD

**Issue by muthuraj57** [facebook/Sonar#41]
<img width="340" alt="screen shot 2018-06-12 at 11 46 55 am" src="https://user-images.githubusercontent.com/10187654/41273875-de89c438-6e38-11e8-8415-532d4339c0f4.png">

Support library classes are packaged with aar instead of resolving it dynamically. And the included support library version is 26.x.x and I'm using 28.0.0-alpha3. There are some breaking changes in 26 to 27 and I can't build my app because of that. 

Ex: For fragments, requireContext method is added in 27 and above which is not available in 26 versions.

Due to some reasons, all my support library method calls points to the bundled version of sonar instead of actual library. Please remove the bundled version so that user can customize the version that suits them.

**Comment by TurKorsaN** [comment]
You can implement sonar like this until they fix it.

debugImplementation ('com.facebook.sonar:sonar:0.0.1'){
        exclude group: 'android'
        exclude group: 'javax'
        exclude group: 'jsr-305'
        exclude group: 'okhttp3'
        exclude group: 'okio'
        exclude group: 'org'
        exclude group: 'com.google'
    }

**Comment by yschimke** [comment]
Just hit this for okhttp

**Comment by yschimke** [comment]
@TurKorsaN that doesn't fix it for me since they are baked into the classes.jar file.

**Comment by passy** [comment]
I think until there's a slim AAR, you would have to use `jarjar` to remove the bundled dependencies.

**Comment by friederbluemle** [comment]
See #24 for a related issue and a temporary hack to fix it (until the packaging problems have been solved).

**Comment by xiphirx** [comment]
Closing in favor of #24
