### ISSUE TITLE
Minor issues in Getting Started guide (Android section)

### ISSUE THREAD

**Issue by friederbluemle** [facebook/Sonar#59]
There are a couple of issue with the [Getting Started guide (Android section)](https://fbsonar.com/docs/getting-started.html#setup-your-android-app). Specifically in this snippet: 

```java
if (BuildConfig.DEBUG && SonarUtils.isMainProcess(mApplicationContext)) {
    final SonarClient client = AndroidSonarClient.getInstance(this);
    client.addPlugin(new MySonarPlugin());
    client.start();
}
```

`isMainProcess` is a _private_ method. Should this be `shouldEnableSonar` instead?

Also, `MySonarPlugin` obviously does not exist. Maybe this could be replaced with an actual plugin and a comment, e.g.:

```java
    // Add plugins here, for example
    client.addPlugin(new NetworkSonarPlugin());
```

That way, you can simply copy+paste from the Getting Started guide and immediately have a working app.

**Comment by passy** [comment]
This was changed here: https://github.com/facebook/Sonar/blob/28be3c7cd85c43880f37f170b14c39403e07458e/docs/getting-started.md

Thanks!
