### ISSUE TITLE
Any iOS SDK released?

### ISSUE THREAD

**Issue by qokelate** [facebook/Sonar#63]
Pod install failed, too more errors....

**CocoaPods could not find compatible versions for pod "PeerTalk":**

Or

**CocoaPods could not find compatible versions for pod "ComponentKit":**

Or

** /xxxxx/Pods/Sonar/xplat/Sonar/SonarWebSocketImpl.cpp:102:8: No member named 'delayedUnsafe' in 'folly::Future<folly::Unit>'  **

..............

**Comment by priteshrnandgaonkar** [comment]
Duplicate of #65
