### ISSUE TITLE
build error for :' Execution failed for task ':app:transformNative_libsWithMergeJniLibsForDev_21Debug'.'

### ISSUE THREAD

**Issue by a1018875550** [facebook/Sonar#72]
Execution failed for task ':app:transformNative_libsWithMergeJniLibsForDev_21Debug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/armeabi-v7a/libgnustl_shared.so
  	File1: ../app/build/intermediates/exploded-aar/com.facebook.react/react-native/0.42.3/jni
  	File2: ../app/build/intermediates/exploded-aar/com.facebook.sonar/sonar/0.0.1/jni

**Comment by priteshrnandgaonkar** [comment]
Closing it in favour of #24
