### ISSUE TITLE
Error: No such module 'SonarKit'

### ISSUE THREAD

**Issue by marina1017** [facebook/Sonar#74]
# Environmental setting
Xcode9.4
Swift4.1
CocoaPods 1.5.2

# Situation
I tried to make workspace by CocoaPods.
<img width="748" alt="screenshot" src="https://user-images.githubusercontent.com/10338059/41417635-e2401cac-7028-11e8-811b-fbee206bf518.png">

I would like to try out the tutorial.

https://fbsonar.com/docs/getting-started.html

```
#import <SonarKit/SonarClient.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#if DEBUG
  SonarClient *client = [SonarClient sharedClient];
  [client addPlugin:[MySonarPlugin new]];
  [client start];
#endif
  ...
}
@end
```

I converted to Swift

```
import SonarKit

class AppDelegate {
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey : Any]? = nil) -> Bool {
#if DEBUG
        let client = SonarClient.shared() as? SonarClient
        client?.add(MySonarPlugin())
        client?.start()
#endif
    }
}
```

I tried `Command + B` but I could not import SonarKit

<img width="839" alt="screenshot" src="https://user-images.githubusercontent.com/10338059/41417650-ec39bc5e-7028-11e8-89da-4d5b327e8ff3.png">

**Comment by priteshrnandgaonkar** [comment]
Currently we don't support Swift. Swift is not compatible with C++. We will need C layer. Closing it for now.
