### ISSUE TITLE
[iOS, CocoaPods(1.5.3) Installation] Typedef redefinition with different types ('uint8_t' (aka 'unsigned char') vs 'enum clockid_t')

### ISSUE THREAD

**Issue by x4snowman** [facebook/Sonar#82]
The compiler  error is from Folly.
 My system is macos 10.13.5 (17F77), Xcode version: 9.4.1 (9F2000). I also installed Xcode 10 beta (10L176w). But I have already use the xcode-select to set the dev path for the Xcode 9.4.1.

**Comment by passy** [comment]
Folly is a separate project: https://github.com/facebook/folly

**Comment by x4snowman** [comment]
@passy Sure, I understand. I tried to  use CocoaPods  to install the Sonar, how can I configure the solve this error?

**Comment by x4snowman** [comment]
@passy Yes, I understood. I updated the issue title. I tried to use CocoaPods to install the Sonar. Is there a way to change Podfile configuration to bypass this compiler error? Do I need to give a specific version of the Folly?

**Comment by passy** [comment]
@x4snowman Sorry, what I meant to say was that if this is an error that is within folly, then it should probably be reported and fixed on their GitHub repo.

**Comment by x4snowman** [comment]
@passy Yes, it's an issue from Folly. However as you provide a guide in the office site[https://fbsonar.com/docs/getting-started.html](url), I think it's appropriate to make the guid work.  I will also report an issue for folly project.  I don't have clue that how teams works with each other in Facebook.  Maybe you can communicate with each other to make the issue been fixed ASAP.  I have spend half my day to setup the Sonar ( By installing all the dependencies manually), but not yet work. By the way, The SonarKit podspec path have updated with iOS prefix #81 , it should be [https://raw.githubusercontent.com/facebook/Sonar/master/iOS/SonarKit.podspec?token=ADr9NBuYoodM_NeysQg899hkxXw0WZ7Xks5bJ5OVwA%3D%3D](url)

**Comment by x4snowman** [comment]
This is fixed on the master branch.
